/* generated by userspace-header-gen.py */
#include <rtems/linkersets.h>
#include "rtems-bsd-qjs-data.h"
/* quickjs-libc.c */
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_qjs, static JSClassDef js_os_timer_class);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_qjs, static JSClassDef js_std_file_class);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_qjs, static JSClassDef js_worker_class);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_qjs, static JSClassID js_os_timer_class_id);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_qjs, static JSClassID js_std_file_class_id);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_qjs, static JSClassID js_worker_class_id);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_qjs, static JSContext *(*js_worker_new_context_func)(JSRuntime *));
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_qjs, static int (*os_poll_func)(JSContext *));
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_qjs, static struct termios oldtty);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_qjs, static uint64_t os_pending_signals);
