/* generated by userspace-header-gen.py */
#include <rtems/linkersets.h>
#include "rtems-bsd-qjs-data.h"
/* quickjs.c */
//RTEMS_LINKER_RWSET_CONTENT(bsd_prog_qjs, static JSAutoInitFunc *js_autoinit_func_table[]);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_qjs, static JSClassID js_class_id_alloc);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_qjs, static pthread_mutex_t js_atomics_mutex);
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_qjs, static struct list_head js_atomics_waiter_list);
