/* generated by userspace-header-gen.py */
#include <rtems/linkersets.h>
#include "rtems-bsd-qjs-data.h"
/* libregexp.c */
RTEMS_LINKER_RWSET_CONTENT(bsd_prog_qjs, static uint16_t const *char_range_table[]);
